// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0bSHqX3TIxHEpNMI_72SmnrdOfOEsrk',
    appId: '1:754976823136:web:b3825c2a1fd52cbac57005',
    messagingSenderId: '754976823136',
    projectId: 'dyslexia-b0b5a',
    authDomain: 'dyslexia-b0b5a.firebaseapp.com',
    storageBucket: 'dyslexia-b0b5a.firebasestorage.app',
    measurementId: 'G-NSM98ZWPYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVu3REZv8PcllV47bPSCbyNiKvfVxW_o',
    appId: '1:754976823136:android:bad0fe79d264e986c57005',
    messagingSenderId: '754976823136',
    projectId: 'dyslexia-b0b5a',
    storageBucket: 'dyslexia-b0b5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB8mZ6mYf0INDsRHeBk_0sSArqKMvaGjY',
    appId: '1:754976823136:ios:32b99ab06c3d3912c57005',
    messagingSenderId: '754976823136',
    projectId: 'dyslexia-b0b5a',
    storageBucket: 'dyslexia-b0b5a.firebasestorage.app',
    iosBundleId: 'com.example.dyslexify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB8mZ6mYf0INDsRHeBk_0sSArqKMvaGjY',
    appId: '1:754976823136:ios:32b99ab06c3d3912c57005',
    messagingSenderId: '754976823136',
    projectId: 'dyslexia-b0b5a',
    storageBucket: 'dyslexia-b0b5a.firebasestorage.app',
    iosBundleId: 'com.example.dyslexify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx0bSHqX3TIxHEpNMI_72SmnrdOfOEsrk',
    appId: '1:754976823136:web:c4c5b18f3829a42bc57005',
    messagingSenderId: '754976823136',
    projectId: 'dyslexia-b0b5a',
    authDomain: 'dyslexia-b0b5a.firebaseapp.com',
    storageBucket: 'dyslexia-b0b5a.firebasestorage.app',
    measurementId: 'G-7992MB3KRB',
  );
}
